### ISSUE TITLE
Firebase database setup

### ISSUE THREAD

**Issue by czachary** [shstan/CS3312_Proj#1]
## Epic Details
- [x] Create firebase db
- [x] Link db to app
- [x] Create definition of db objects
- [x] Populate db for testing
- [x] Link UI to backend

## Acceptance Scenarios
Given: A user opens the app
When: he/she tries to login/register
Then: the database is successfully accessed 

## Done Done Criteria
- Code is merged with master branch, unit tests coded and passing, and acceptance test passing
